// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ctesp2022_final_gg.Database;

namespace ctesp2022_final_gg.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20220210132038_insertData")]
    partial class insertData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ctesp2022_final_gg.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contacto")
                        .HasColumnType("int");

                    b.Property<string>("Morada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Contacto = 123,
                            Morada = "Rua Direita 1",
                            NomeCliente = "Antonio"
                        },
                        new
                        {
                            ClienteId = 2,
                            Contacto = 456,
                            Morada = "Rua Esquerda 1",
                            NomeCliente = "Jose"
                        });
                });

            modelBuilder.Entity("ctesp2022_final_gg.ContaBancaria", b =>
                {
                    b.Property<int>("ContaBancariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("IBAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroConta")
                        .HasColumnType("int");

                    b.Property<double>("SaldoCorrente")
                        .HasColumnType("float");

                    b.HasKey("ContaBancariaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ContaBancaria");

                    b.HasData(
                        new
                        {
                            ContaBancariaId = 1,
                            ClienteId = 1,
                            IBAN = "PT50-123",
                            NumeroConta = 1,
                            SaldoCorrente = 100.0
                        },
                        new
                        {
                            ContaBancariaId = 2,
                            ClienteId = 2,
                            IBAN = "PT50-456",
                            NumeroConta = 2,
                            SaldoCorrente = 200.0
                        });
                });

            modelBuilder.Entity("ctesp2022_final_gg.TipoTransacao", b =>
                {
                    b.Property<int>("TipoTransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeTipoTransacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TipoTransacaoId");

                    b.ToTable("TipoTransacao");

                    b.HasData(
                        new
                        {
                            TipoTransacaoId = 1,
                            NomeTipoTransacao = "Credito"
                        },
                        new
                        {
                            TipoTransacaoId = 2,
                            NomeTipoTransacao = "Debito"
                        });
                });

            modelBuilder.Entity("ctesp2022_final_gg.Transacao", b =>
                {
                    b.Property<int>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoTransacaoId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("TransacaoId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("TipoTransacaoId");

                    b.ToTable("Transacao");

                    b.HasData(
                        new
                        {
                            TransacaoId = 1,
                            ContaBancariaId = 1,
                            Dia = new DateTime(2022, 2, 8, 13, 20, 37, 886, DateTimeKind.Local).AddTicks(634),
                            TipoTransacaoId = 1,
                            Valor = 100.0
                        },
                        new
                        {
                            TransacaoId = 2,
                            ContaBancariaId = 2,
                            Dia = new DateTime(2022, 2, 9, 13, 20, 37, 888, DateTimeKind.Local).AddTicks(4354),
                            TipoTransacaoId = 1,
                            Valor = 200.0
                        });
                });

            modelBuilder.Entity("ctesp2022_final_gg.ContaBancaria", b =>
                {
                    b.HasOne("ctesp2022_final_gg.Cliente", "Cliente")
                        .WithMany("ContaBancarias")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ctesp2022_final_gg.Transacao", b =>
                {
                    b.HasOne("ctesp2022_final_gg.ContaBancaria", "ContaBancaria")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ctesp2022_final_gg.TipoTransacao", "TipoTransacao")
                        .WithMany()
                        .HasForeignKey("TipoTransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaBancaria");

                    b.Navigation("TipoTransacao");
                });

            modelBuilder.Entity("ctesp2022_final_gg.Cliente", b =>
                {
                    b.Navigation("ContaBancarias");
                });

            modelBuilder.Entity("ctesp2022_final_gg.ContaBancaria", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
