version: '3'

services:
  db:
    build: ./Db
    hostname: sqlserver
    container_name: sqlserver
    ports:
        - 1433:1433
    volumes: 
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
      - data:/docker-entrypoint-initdb.d
  api:
    build:
      context: ../../../.
      dockerfile: ctesp2022-final-gg/Docker/PROD/API/Dockerfile
    hostname: api
    container_name: api
    ports:
      - 8050:80
    depends_on: 
      - db
  
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
  data: